const Albuns = [
  "Frank Sinatra - In The Wee Small Hours",
  "Elvis Presley - Elvis Presley",
  "The Louvin Brothers - Tragic Songs Of Life",
  "Louis Prima Featuring Keely Smith With Sam Butera And The Witnesses - The Wildest!",
  "Fats Domino - This Is Fats",
  "Duke Ellington And His Orchestra - Ellington At Newport",
  "Frank Sinatra - Songs For Swingin' Lovers",
  'The Crickets (2) - The "Chirping" Crickets',
  "Count Basie And His Orchestra* + Neal Hefti - Basie",
  "Thelonious Monk - Brilliant Corners",
  "Sabu* - Palo Congo",
  "Miles Davis - Birth Of The Cool",
  "Machito And His Orchestra - Kenya Afro Cuban Jazz",
  "Little Richard - Here's Little Richard",
  "Tito Puente And His Orchestra - Dance Mania",
  "Billie Holiday With Ray Ellis And His Orchestra - Lady In Satin",
  "Jack Elliott* - Jack Takes The Floor",
  "Sarah Vaughan And Her Trio - Sarah Vaughan At Mister Kelly's",
  "Ella Fitzgerald - Ella Fitzgerald Sings The Gershwin Song Book Vol. 1",
  "Ray Charles - The Genius Of Ray Charles",
  "Miles Davis - Kind Of Blue",
  "Marty Robbins - Gunfighter Ballads And Trail Songs",
  "The Dave Brubeck Quartet - Time Out",
  "Joan Baez - Joan Baez",
  "Elvis Presley - Elvis Is Back!",
  "Miriam Makeba - Miriam Makeba",
  "The Everly Brothers* - A Date With The Everly Brothers",
  "The Incredible Jimmy Smith* - Back At The Chicken Shack",
  "Muddy Waters - Muddy Waters At Newport 1960",
  "Bill Evans Trio* Featuring Scott La Faro* - Sunday At The Village Vanguard",
  "Ray Charles - Modern Sounds In Country And Western Music",
  "Booker T. & The M.G.s* - Green Onions",
  "Stan Getz / Charlie Byrd - Jazz Samba",
  "Ray Price - Night Life",
  "The Beatles - With The Beatles",
  "Bob Dylan - The Freewheelin' Bob Dylan",
  "Various - A Christmas Gift For You From Philles Records",
  "Sam Cooke - Live At The Harlem Square Club 1963",
  "Mingus* - The Black Saint And The Sinner Lady",
  "James Brown - James Brown Live At The Apollo",
  "Stan Getz / Joao Gilberto* Featuring Antonio Carlos Jobim - Getz / Gilberto",
  "The Beatles - A Hard Day's Night",
  "Jacques Brel - Olympia 64",
  "Solomon Burke - Rock 'N Soul",
  "Dusty Springfield - A Girl Called Dusty",
  "The Rolling Stones - The Rolling Stones",
  "Buck Owens And His Buckaroos - I've Got A Tiger By The Tail",
  'Jerry Lee Lewis And The Nashville Teens - "Live" At The Star-Club, Hamburg',
  "The Sonics - Here Are The Sonics!!!",
  "Bob Dylan - Bringing It All Back Home",
  "Otis Redding - Otis Blue / Otis Redding Sings Soul",
  "The Beach Boys - The Beach Boys Today!",
  "John Coltrane - A Love Supreme",
  "B.B. King - Live At The Regal",
  "The Beatles - Rubber Soul",
  "Bert Jansch - Bert Jansch",
  "The Byrds - Mr. Tambourine Man",
  "Bob Dylan - Highway 61 Revisited",
  "The Who - My Generation",
  "The Beatles - Revolver",
  "The Beach Boys - Pet Sounds",
  "Fred Neil - Fred Neil",
  "The Byrds - Fifth Dimension",
  "Bob Dylan - Blonde On Blonde",
  "Monks* - Black Monk Time",
  "The Kinks - Face To Face",
  "The Mama's And The Papa's* - If You Can Believe Your Eyes And Ears",
  "Paul Revere & The Raiders - Midnight Ride",
  "The Mothers Of Invention* - Freak Out!",
  "The Rolling Stones - Aftermath",
  "Simon & Garfunkel - Parsley, Sage, Rosemary And Thyme",
  "The 13th Floor Elevators* - The Psychedelic Sounds Of The 13th Floor Elevators",
  "John Mayall With Eric Clapton - Blues Breakers",
  "Yardbirds* - Yardbirds",
  "Nina Simone - Wild Is The Wind",
  "Astrud Gilberto - Beach Samba",
  "Nico (3) - Chelsea Girl",
  "The Beatles - Sgt. Pepper's Lonely Hearts Club Band",
  "Country Joe & The Fish* - Electric Music For The Mind And Body",
  "Buffalo Springfield - Buffalo Springfield Again",
  "Captain Beefheart And His Magic Band - Safe As Milk",
  "Moby Grape - Moby Grape",
  "Love - Da Capo",
  "The Beau Brummels - Triangle",
  "The Monkees - Headquarters",
  "Tim Buckley - Goodbye And Hello",
  "Love - Forever Changes",
  "Cream (2) - Disraeli Gears",
  "Pink Floyd - The Piper At The Gates Of Dawn",
  "The Who - The Who Sell Out",
  "The Velvet Underground & Nico (3) - The Velvet Underground & Nico",
  "Francis Albert Sinatra*, Antonio Carlos Jobim - Francis Albert Sinatra & Antonio Carlos Jobim",
  "The Doors - The Doors",
  "The Byrds - Younger Than Yesterday",
  "The Young Rascals - Groovin'",
  "Jefferson Airplane - Surrealistic Pillow",
  "The Kinks - Something Else By The Kinks",
  "Donovan - Sunshine Superman",
  "Merle Haggard And The Strangers - I'm A Lonesome Fugitive",
  "The Jimi Hendrix Experience - Are You Experienced",
  "The Electric Prunes - The Electric Prunes",
  "Loretta Lynn - Don't Come Home A Drinkin' (With Lovin' On Your Mind)",
  "Shivkumar Sharma* - Hariprasad Chaurasia - Brijbhushan Kabra* - Call Of The Valley",
  "The Velvet Underground - White Light/White Heat",
  "The Jimi Hendrix Experience - Axis: Bold As Love",
  "Aretha Franklin - I Never Loved A Man The Way I Love You",
  "The Rolling Stones - Beggars Banquet",
  "Traffic - Traffic",
  "The Incredible String Band - The Hangman's Beautiful Daughter",
  "The Kinks - The Kinks Are The Village Green Preservation Society",
  "Ravi Shankar - The Sounds Of India",
  "Os Mutantes - Os Mutantes",
  "The Jimi Hendrix Experience - Electric Ladyland",
  "Leonard Cohen - Songs Of Leonard Cohen",
  "Johnny Cash - At Folsom Prison",
  "Laura Nyro - Eli And The Thirteenth Confession",
  "Aretha Franklin - Lady Soul",
  "Blue Cheer - Vincebus Eruptum",
  "The Byrds - The Notorious Byrd Brothers",
  "Big Brother & The Holding Company - Cheap Thrills",
  "The United States Of America - The United States Of America",
  "Dr. John, The Night Tripper* - Gris-Gris",
  "Iron Butterfly - In-A-Gadda-Da-Vida",
  "Pretty Things* - S. F. Sorrow",
  "Simon & Garfunkel - Bookends",
  "Small Faces - Ogdens' Nut Gone Flake",
  "The Band - Music From Big Pink",
  "Jeff Beck - Truth",
  "Caetano Veloso - Caetano Veloso",
  "Scott Walker - Scott 2",
  "The Zombies - Odessey And Oracle",
  "Van Morrison - Astral Weeks",
  "The Byrds - Sweetheart Of The Rodeo",
  "The Beatles - The Beatles",
  "The Mothers Of Invention* - We're Only In It For The Money",
  "Neil Young With Crazy Horse* - Everybody Knows This Is Nowhere",
  "Captain Beefheart & His Magic Band* - Trout Mask Replica",
  "Creedence Clearwater Revival - Bayou Country",
  "Crosby, Stills & Nash - Crosby, Stills & Nash",
  "Blood, Sweat And Tears - Blood, Sweat And Tears",
  "The Flying Burrito Bros - The Gilded Palace Of Sin",
  "Johnny Cash - Johnny Cash At San Quentin",
  "Creedence Clearwater Revival - Green River",
  "The Beatles - Abbey Road",
  "The Who - Tommy",
  "Miles Davis - In A Silent Way",
  "The Bee Gees* - Odessa",
  "The Pentangle* - Basket Of Light",
  "Rolling Stones* - Let It Bleed",
  "Nick Drake - Five Leaves Left",
  "Dusty Springfield - Dusty In Memphis",
  "Elvis Presley - From Elvis In Memphis",
  "The Velvet Underground - The Velvet Underground",
  "Quicksilver Messenger Service - Happy Trails",
  "Led Zeppelin - Led Zeppelin",
  "The Band - The Band",
  "Led Zeppelin - Led Zeppelin II",
  "MC5 - Kick Out The Jams",
  "The Temptations - Cloud Nine",
  "Sly & The Family Stone - Stand!",
  "Tim Buckley - Happy Sad",
  "Chicago Transit Authority* - Chicago Transit Authority",
  "Fairport Convention - Unhalfbricking",
  "The Youngbloods - Elephant Mountain",
  "Isaac Hayes - Hot Buttered Soul",
  "The Grateful Dead - Live/Dead",
  "The Kinks - Arthur Or The Decline And Fall Of The British Empire",
  "King Crimson - In The Court Of The Crimson King (An Observation By King Crimson)",
  "Leonard Cohen - Songs From A Room",
  "Fairport Convention - Liege & Lief",
  "Scott Engel - Scott 4",
  "The Stooges - The Stooges",
  "Alexander Spence - Oar",
  "Frank Zappa - Hot Rats",
  "Creedence Clearwater Revival - Cosmo's Factory",
  "Derek And The Dominos* - Layla And Other Assorted Love Songs",
  "Miles Davis - Bitches Brew",
  "Spirit (8) - Twelve Dreams Of Dr. Sardonicus",
  "Black Sabbath - Black Sabbath",
  "The Doors - Morrison Hotel",
  "Carpenters - Close To You",
  "Stephen Stills - Stephen Stills",
  "John Lennon / Plastic Ono Band* - John Lennon / Plastic Ono Band",
  "Crosby, Stills, Nash & Young - Déjà Vu",
  "Black Sabbath - Paranoid",
  "Neil Young - After The Gold Rush",
  "Led Zeppelin - Led Zeppelin III",
  "Deep Purple - Deep Purple In Rock",
  "Van Morrison - Moondance",
  "Grateful Dead* - American Beauty",
  "Nick Drake - Bryter Layter",
  "Ananda Shankar - Ananda Shankar",
  "The Who - Live At Leeds",
  "Soft Machine - Third",
  "Rod Stewart - Gasoline Alley",
  "George Harrison - All Things Must Pass",
  "Simon And Garfunkel* - Bridge Over Troubled Water",
  "Cat Stevens - Tea For The Tillerman",
  "Traffic - John Barleycorn Must Die",
  "The Stooges - Fun House",
  "James Taylor (2) - Sweet Baby James",
  "McCartney* - McCartney",
  "Santana - Abraxas",
  "Syd Barrett - The Madcap Laughs",
  "Jethro Tull - Aqualung",
  "David Crosby - If I Could Only Remember My Name",
  "Sly & The Family Stone - There's A Riot Goin' On",
  "Marvin Gaye - What's Going On",
  "Yes - The Yes Album",
  "Bee Gees - Trafalgar",
  "The Who - Who's Next",
  "Carole King - Tapestry",
  "Isaac Hayes - Shaft",
  "The Allman Brothers Band - The Allman Brothers Band At Fillmore East",
  "The Rolling Stones - Sticky Fingers",
  "John Lennon - Imagine",
  "The Beach Boys - Surf's Up",
  "Yes - Fragile",
  "The Doors - L.A. Woman",
  "Can - Tago Mago",
  "Elton John - Madman Across The Water",
  "Dolly Parton - Coat Of Many Colors",
  "Don McLean - American Pie",
  "Emerson, Lake & Palmer - Tarkus",
  "Led Zeppelin - Untitled",
  "Serge Gainsbourg - Histoire De Melody Nelson",
  "Rod Stewart - Every Picture Tells A Story",
  "Emerson, Lake & Palmer - Pictures At An Exhibition",
  "Leonard Cohen - Songs Of Love And Hate",
  "Joni Mitchell - Blue",
  "Funkadelic - Maggot Brain",
  "Janis Joplin - Pearl",
  "Fela Ransome-Kuti* And The Africa '70* With Ginger Baker - Live!",
  "Faces (3) - A Nod's As Good As A Wink...To A Blind Horse",
  "The Flamin' Groovies - Teenage Head",
  "Gene Clark - White Light",
  "John Prine - John Prine",
  "Nilsson* - Nilsson Schmilsson",
  "T. Rex - Electric Warrior",
  "David Bowie - Hunky Dory",
  "Randy Newman - Sail Away",
  "Deep Purple - Machine Head",
  "Big Star - #1 Record",
  "Black Sabbath - Black Sabbath Vol 4",
  "Steely Dan - Can't Buy A Thrill",
  "Neil Young - Harvest",
  "Curtis Mayfield - Super Fly",
  "Slade - Slayed?",
  "Deep Purple - Made In Japan",
  "Yes - Close To The Edge",
  "Lou Reed - Transformer",
  "Hugh Masekela - Home Is Where The Music Is",
  "Milton Nascimento & Lô Borges* - Clube Da Esquina",
  "Todd Rundgren - Something / Anything?",
  "Nitty Gritty Dirt Band - Will The Circle Be Unbroken",
  "Stevie Wonder - Talking Book",
  "Stephen Stills / Manassas - Manassas",
  "T. Rex - The Slider",
  "David Ackles - American Gothic",
  "Eagles - Eagles",
  "Tim Buckley - Greetings From L.A.",
  "Nick Drake - Pink Moon",
  "Paul Simon - Paul Simon",
  "Roxy Music - Roxy Music",
  "Alice Cooper - School's Out",
  "The Temptations - All Directions",
  "David Bowie - The Rise And Fall Of Ziggy Stardust And The Spiders From Mars",
  "War - The World Is A Ghetto",
  "Al Green - Let's Stay Together",
  "Rolling Stones* - Exile On Main St.",
  "Lynyrd Skynyrd - (Pronounced 'Lĕh-'nérd 'Skin-'nérd)",
  "Michael Viner's Incredible Bongo Band* - Bongo Rock",
  "David Bowie - Aladdin Sane",
  "King Crimson - Larks' Tongues In Aspic",
  "The Wailers - Catch A Fire",
  "Hawkwind - Space Ritual",
  "John Cale - Paris 1919",
  "Can - Future Days",
  "Lou Reed - Berlin",
  "Genesis - Selling England By The Pound",
  "Marvin Gaye - Let's Get It On",
  "John Martyn - Solid Air",
  "Roxy Music - For Your Pleasure",
  "Faust - Faust IV",
  "Herbie Hancock - Head Hunters",
  "Mott The Hoople - Mott",
  "Mike Oldfield - Tubular Bells",
  "Todd Rundgren - A Wizard, A True Star",
  "Elton John - Goodbye Yellow Brick Road",
  "Steely Dan - Countdown To Ecstasy",
  "Waylon Jennings - Honky Tonk Heroes",
  "Pink Floyd - The Dark Side Of The Moon",
  "Stevie Wonder - Innervisions",
  "ZZ Top - Tres Hombres",
  "Paul McCartney And Wings* - Band On The Run",
  "The Sensational Alex Harvey Band - Next",
  "Alice Cooper - Billion Dollar Babies",
  "Iggy And The Stooges* - Raw Power",
  "The Isley Brothers - 3 + 3",
  "New York Dolls - New York Dolls",
  "Eno* - Here Come The Warm Jets",
  "Bad Company (3) - Bad Co",
  "Genesis - The Lamb Lies Down On Broadway",
  "Shuggie Otis - Inspiration Information",
  "Stevie Wonder - Fulfillingness' First Finale",
  "Eric Clapton - 461 Ocean Boulevard",
  "Kraftwerk - Autobahn",
  "Van Morrison - It's Too Late To Stop Now",
  "Joni Mitchell - Court And Spark",
  "Queen - Queen II",
  "Roxy Music - Country Life",
  "Tangerine Dream - Phaedra",
  "Sparks - Kimono My House",
  "Supertramp - Crime Of The Century",
  "Richard & Linda Thompson - I Want To See The Bright Lights Tonight",
  "Gil Scott-Heron / Brian Jackson* - Winter In America",
  "Queen - Sheer Heart Attack",
  "10cc - Sheet Music",
  "Neil Young - On The Beach",
  "George Jones (2) - The Grand Tour",
  "Gene Clark - No Other",
  "Steely Dan - Pretzel Logic",
  "Randy Newman - Good Old Boys",
  "Bob Marley & The Wailers - Natty Dread",
  "Robert Wyatt - Rock Bottom",
  "Gram Parsons - Grievous Angel",
  "Eno* - Another Green World",
  "The Dictators - Go Girl Crazy!",
  "Neu! - Neu! '75",
  "Led Zeppelin - Physical Graffiti",
  "Keith Jarrett - The Köln Concert",
  "Aerosmith - Toys In The Attic",
  "David Bowie - Young Americans",
  "Burning Spear - Marcus Garvey",
  "Bruce Springsteen - Born To Run",
  "Emmylou Harris - Pieces Of The Sky",
  "Dion (3) - Born To Be With You",
  "Joni Mitchell - The Hissing Of Summer Lawns",
  "Tom Waits - Nighthawks At The Diner",
  "R. D. Burman - Shalimar",
  "Neil Young - Tonight's The Night",
  "Bob Dylan - Blood On The Tracks",
  "Patti Smith - Horses",
  "Pink Floyd - Wish You Were Here",
  "Queen - A Night At The Opera",
  "Willie Nelson - Red Headed Stranger",
  "Earth, Wind & Fire - That's The Way Of The World",
  "Curtis Mayfield - (There's No Place Like) America Today",
  "Tom Petty And The Heartbreakers - Tom Petty And The Heartbreakers",
  "The Modern Lovers - The Modern Lovers",
  "David Bowie - Station To Station",
  "Joni Mitchell - Hejira",
  "Boston - Boston",
  "Eagles - Hotel California",
  "ABBA - Arrival",
  "Kiss - Destroyer",
  "Rush - 2112",
  "Jorge Ben - África Brasil",
  "Joan Armatrading - Joan Armatrading",
  "Aerosmith - Rocks",
  "Parliament - Mothership Connection",
  "Simon Jeffes - Performed By Members Of The Penguin Café Orchestra* - Music From The Penguin Café",
  "Jean Michel Jarre* - Oxygene",
  "Ramones - Ramones",
  "Fẹla* And Afrika 70* - Zombie",
  "Peter Tosh - Legalize It",
  "Stevie Wonder - Songs In The Key Of Life",
  "Peter Frampton - Frampton Comes Alive!",
  "Brian Eno - Before And After Science",
  "Kraftwerk - Trans Europa Express",
  "Billy Joel - The Stranger",
  "Bob Marley & The Wailers - Exodus",
  "Electric Light Orchestra - Out Of The Blue",
  "Weather Report - Heavy Weather",
  "Muddy Waters - Hard Again",
  "The Stranglers - Rattus Norvegicus",
  "The Clash - The Clash",
  "David Bowie - Low",
  "Steely Dan - Aja",
  "Wire - Pink Flag",
  "John Martyn - One World",
  "Talking Heads - Talking Heads: 77",
  "Fleetwood Mac - Rumours",
  'David Bowie - "Heroes"',
  "Dennis Wilson (2) - Pacific Ocean Blue",
  "Suicide - Suicide",
  "Iggy Pop - The Idiot",
  "Peter Gabriel - Peter Gabriel",
  "Television - Marquee Moon",
  "Meat Loaf - Bat Out Of Hell",
  "Elvis Costello - My Aim Is True",
  "Iggy Pop - Lust For Life",
  "Ian Dury - New Boots And Panties!!",
  "Sex Pistols - Never Mind The Bollocks Here's The Sex Pistols",
  "Pere Ubu - The Modern Dance",
  "Kraftwerk - Die Mensch·Maschine",
  "Blondie - Parallel Lines",
  "Elis Regina - Vento De Maio",
  "Pere Ubu - Dub Housing",
  "The Only Ones - The Only Ones",
  "Elvis Costello & The Attractions - This Year's Model",
  "The Jam - All Mod Cons",
  "Joe Ely - Honky Tonk Masquerade",
  "The Adverts - Crossing The Red Sea With The Adverts",
  "Big Star - 3rd",
  "The Residents - Duck Stab / Buster & Glen",
  "Public Image* - Public Image (First Issue)",
  "Magazine - Real Life",
  "Bruce Springsteen - Darkness On The Edge Of Town",
  "Funkadelic - One Nation Under A Groove",
  "Throbbing Gristle - D.o.A. The Third And Final Report",
  "Thin Lizzy - Live And Dangerous",
  "Talking Heads - More Songs About Buildings And Food",
  "Buzzcocks - Another Music In A Different Kitchen",
  "Van Halen - Van Halen",
  "Willie Colon* & Ruben Blades - Siembra",
  "The Cars - The Cars",
  "Devo - Q: Are We Not Men? A: We Are Devo!",
  "Dire Straits - Dire Straits",
  "The Saints (2) - Eternally Yours",
  "Marvin Gaye - Here, My Dear",
  "Willie Nelson - Stardust",
  "Chic - C'est Chic",
  "X-Ray Spex - Germfree Adolescents",
  "Brian Eno - Ambient 1 (Music For Airports)",
  "Siouxsie And The Banshees* - The Scream",
  "AC/DC - Highway To Hell",
  "Sister Sledge - We Are Family",
  "Crusaders* - Street Life",
  "Germs - (GI)",
  "The B-52's - The B-52's",
  "Holger Czukay - Movies",
  "The Police - Reggatta De Blanc",
  "The Fall - Live At The Witch Trials",
  "Talking Heads - Fear Of Music",
  "Joy Division - Unknown Pleasures",
  "Chic - Risqué",
  "The Undertones - The Undertones",
  "The Clash - London Calling",
  "Japan - Quiet Life",
  "Marianne Faithfull - Broken English",
  "The Slits - Cut",
  "Elvis Costello And The Attractions* - Armed Forces",
  "Neil Young & Crazy Horse - Rust Never Sleeps",
  "Gang Of Four - Entertainment!",
  "Cheap Trick - Cheap Trick At Budokan",
  "Fleetwood Mac - Tusk",
  "Pink Floyd - The Wall",
  "PiL* - Metal Box",
  "Michael Jackson - Off The Wall",
  "The Damned - Machine Gun Etiquette",
  "Gary Numan - The Pleasure Principle",
  "Specials* - Specials",
  "Adam And The Ants - Kings Of The Wild Frontier",
  "Dexy's Midnight Runners* - Searching For The Young Soul Rebels",
  "AC/DC - Back In Black",
  "The Cramps - Songs The Lord Taught Us",
  "Dead Kennedys - Fresh Fruit For Rotting Vegetables",
  "Peter Gabriel - Peter Gabriel",
  "The Soft Boys - Underwater Moonlight",
  "The Cure - Seventeen Seconds",
  "Echo And The Bunnymen* - Crocodiles",
  "Motörhead - Ace Of Spades",
  "Killing Joke - Killing Joke",
  "Judas Priest - British Steel",
  "Circle Jerks - Group Sex",
  "Talking Heads - Remain In Light",
  "Joy Division - Closer",
  "Iron Maiden - Iron Maiden",
  "The Undertones - Hypnotised",
  "The Jam - Sound Affects",
  "Tom Waits - Heartattack And Vine",
  "UB40 - Signing Off",
  "The Teardrop Explodes - Kilimanjaro",
  "The Specials - More Specials",
  "Steve Winwood - Arc Of A Diver",
  "Pretenders* - Pretenders",
  "Einstürzende Neubauten - Kollaps",
  "Siouxsie And The Banshees* - Juju",
  "Heaven 17 - Penthouse And Pavement",
  "Go-Go's - Beauty And The Beat",
  "Motörhead - No Sleep 'til Hammersmith",
  "Soft Cell - Non-Stop Erotic Cabaret",
  "Orchestral Manoeuvres In The Dark - Architecture & Morality",
  "Brian Eno - David Byrne - My Life In The Bush Of Ghosts",
  "Black Flag - Damaged",
  "X (5) - Wild Gift",
  "The Psychedelic Furs - Talk Talk Talk",
  "The Human League - Dare",
  "The Gun Club - Fire Of Love",
  "Bauhaus - Mask",
  "Bobby Womack - The Poet",
  "Tom Tom Club - Tom Tom Club",
  "Rush - Moving Pictures",
  "ABBA - The Visitors",
  "ABC - The Lexicon Of Love",
  "Prince - 1999",
  "Grandmaster Flash & The Furious Five - The Message",
  "Elvis Costello And The Attractions* - IbMePdErRoIoAmL (Imperial Bedroom)",
  "The Cure - Pornography",
  "Kevin Rowland & Dexys Midnight Runners - Too-Rye-Ay",
  "Simple Minds - New Gold Dream (81-82-83-84)",
  "Madness - The Rise And Fall",
  "Donald Fagen - The Nightfly",
  "Haircut One Hundred - Pelican West",
  "Kate Bush - The Dreaming",
  "Orange Juice (3) - Rip It Up",
  "Michael Jackson - Thriller",
  "The Birthday Party - Junkyard",
  "Venom (8) - Black Metal",
  "Bruce Springsteen - Nebraska",
  "Associates* - Sulk",
  "Iron Maiden - The Number Of The Beast",
  "Duran Duran - Rio",
  "Violent Femmes - Violent Femmes",
  "Malcolm McLaren - Duck Rock",
  "Def Leppard - Pyromania",
  "R.E.M. - Murmur",
  "The The - Soul Mining",
  "Tom Waits - Swordfishtrombones",
  "The Blue Nile - A Walk Across The Rooftops",
  "Hanoi Rocks - Back To Mystery City",
  "Cyndi Lauper - She's So Unusual",
  "Paul Simon - Hearts And Bones",
  "Echo & The Bunnymen - Porcupine",
  "ZZ Top - Eliminator",
  "Eurythmics - Sweet Dreams (Are Made Of This)",
  "U2 - War",
  "The Police - Synchronicity",
  "Meat Puppets - Meat Puppets II",
  "Culture Club - Colour By Numbers",
  "Frankie Goes To Hollywood - Welcome To The Pleasuredome",
  "Run-D.M.C.* - Run-D.M.C.",
  "Sade - Diamond Life",
  "Cocteau Twins - Treasure",
  "Minor Threat - Out Of Step",
  "Van Halen - 1984",
  "Prince And The Revolution - Purple Rain",
  "The Replacements - Let It Be",
  "The Style Council - Café Bleu",
  "Tina Turner - Private Dancer",
  "Echo & The Bunnymen - Ocean Rain",
  "Minutemen - Double Nickels On The Dime",
  "Lloyd Cole & The Commotions - Rattlesnakes",
  "Youssou N'Dour & Le Super Etoile De Dakar - Immigrés / Bitm Rew",
  "Bruce Springsteen - Born In The U.S.A.",
  "The Fall - This Nation's Saving Grace",
  "Abdullah Ibrahim - Water From An Ancient Well",
  "a-ha - Hunting High And Low",
  "Tears For Fears - Songs From The Big Chair",
  "Dire Straits - Brothers In Arms",
  "Prefab Sprout - Steve McQueen",
  "Mekons* - Fear And Whiskey",
  "Big Black - Atomizer",
  "Suzanne Vega - Suzanne Vega",
  "The Pogues - Rum Sodomy & The Lash",
  "Kate Bush - Hounds Of Love",
  "The Smiths - Meat Is Murder",
  "Tom Waits - Rain Dogs",
  "The Jesus And Mary Chain - Psychocandy",
  "New Order - Low-life",
  "Simply Red - Picture Book",
  "Dexys Midnight Runners - Don't Stand Me Down",
  "Scritti Politti - Cupid & Psyche 85",
  "Elvis Costello And The Attractions* - Blood & Chocolate",
  "Afrika Bambaataa & Soulsonic Force - Planet Rock - The Album",
  "Beastie Boys - Licensed To Ill",
  "Metallica - Master Of Puppets",
  "The The - Infected",
  "Nanci Griffith - Last Of The True Believers",
  "Billy Bragg - Talking With The Taxman About Poetry",
  "Talk Talk - The Colour Of Spring",
  "Megadeth - Peace Sells... But Who's Buying?",
  "Bon Jovi - Slippery When Wet",
  "Sonic Youth - EVOL",
  "Slayer - Reign In Blood",
  "Throwing Muses - Throwing Muses",
  "Paul Simon - Graceland",
  "Run DMC* - Raising Hell",
  "XTC - Skylarking",
  "Steve Earle - Guitar Town",
  "Bad Brains - I Against I",
  "Anita Baker - Rapture",
  "The Smiths - The Queen Is Dead",
  "Peter Gabriel - So",
  "Anthrax - Among The Living",
  "Dinosaur* - You're Living All Over Me",
  "Dolly Parton, Linda Ronstadt & Emmylou Harris - Trio",
  "Def Leppard - Hysteria",
  "R.E.M. - Document",
  'Prince - Sign "O" The Times',
  "The Cult - Electric",
  "Depeche Mode - Music For The Masses",
  "The Sisters Of Mercy - Floodland",
  "George Michael - Faith",
  "Hüsker Dü - Warehouse: Songs And Stories",
  "Butthole Surfers - Locust Abortion Technician",
  "Astor Piazzolla & Gary Burton - The New Tango",
  "The Smiths - Strangeways, Here We Come",
  "Guns N' Roses - Appetite For Destruction",
  "The Jesus And Mary Chain - Darklands",
  "Ladysmith Black Mambazo - Shaka Zulu",
  "Laibach - Opus Dei",
  "Napalm Death - Scum",
  "Sonic Youth - Sister",
  "The Triffids - Calenture",
  "Michael Jackson - Bad",
  "Pet Shop Boys - Actually",
  "U2 - The Joshua Tree",
  "Terence Trent D'Arby - Introducing The Hardline According To Terence Trent D'Arby",
  "The Pogues - If I Should Fall From Grace With God",
  "Leonard Cohen - I'm Your Man",
  "The Waterboys - Fisherman's Blues",
  "Fishbone - Truth And Soul",
  "Everything But The Girl - Idlewild",
  "Living Colour - Vivid",
  "Mudhoney - Superfuzz Bigmuff",
  "R.E.M. - Green",
  "Happy Mondays - Bummed",
  "The Go-Betweens - 16 Lovers Lane",
  "Cowboy Junkies - The Trinity Session",
  "Tracy Chapman - Tracy Chapman",
  "My Bloody Valentine - Isn't Anything",
  "Pixies - Surfer Rosa",
  "Metallica - ...And Justice For All",
  "Dinosaur Jr. - Bug",
  "Dagmar Krause - Tank Battles: The Songs Of Hanns Eisler",
  "k.d. lang - Shadowland",
  "American Music Club - California",
  "Morrissey - Viva Hate",
  "Sonic Youth - Daydream Nation",
  "The Sugarcubes - Life's Too Good",
  "Dwight Yoakam - Buenas Noches From A Lonely Room",
  "Jane's Addiction - Nothing's Shocking",
  "Public Enemy - It Takes A Nation Of Millions To Hold Us Back",
  "Faith No More - The Real Thing",
  "Lenny Kravitz - Let Love Rule",
  "John Lee Hooker - The Healer",
  "Neworder* - Technique",
  "Madonna - Like A Prayer",
  "Queen Latifah - All Hail The Queen",
  "Spacemen 3 - Playing With Fire",
  "fIREHOSE - fROMOHIO",
  "Beastie Boys - Paul's Boutique",
  "The Young Gods - L'Eau Rouge - Red Water",
  "John Zorn - Spy Vs. Spy: The Music Of Ornette Coleman",
  "The Stone Roses - The Stone Roses",
  "Neneh Cherry - Raw Like Sushi",
  "Baaba Maal & Mansour Seck - Djam Leelii",
  "Kate Bush - The Sensual World",
  "The Cure - Disintegration",
  "808 State - Ninety",
  "Coldcut - What's That Noise?",
  "Barry Adamson - Moss Side Story",
  "Aerosmith - Pump",
  "Pixies - Doolittle",
  "Bonnie Raitt - Nick Of Time",
  "Fugazi - Repeater",
  "Soul II Soul - Club Classics Vol. One",
  "De La Soul - 3 Feet High And Rising",
  "Janet Jackson - Rhythm Nation 1814",
  "Jungle Brothers - Done By The Forces Of Nature",
  "N.W.A* - Straight Outta Compton",
  "Cocteau Twins - Heaven Or Las Vegas",
  "The Shamen - En-Tact",
  "Deee-Lite - World Clique",
  "The La's - The La's",
  "The Black Crowes - Shake Your Money Maker",
  "Depeche Mode - Violator",
  "Pixies - Bossanova",
  "Megadeth - Rust In Peace",
  "Digital Underground - Sex Packets",
  "Pet Shop Boys - Behaviour",
  "Happy Mondays - Pills 'N' Thrills And Bellyaches",
  "George Michael - Listen Without Prejudice Vol. 1",
  "Neil Young + Crazy Horse* - Ragged Glory",
  "Ice Cube - AmeriKKKa's Most Wanted",
  "Jane's Addiction - Ritual De Lo Habitual",
  "L.L. Cool J* - Mama Said Knock You Out",
  "Public Enemy - Fear Of A Black Planet",
  "Sinéad O'Connor - I Do Not Want What I Haven't Got",
  "A Tribe Called Quest - People's Instinctive Travels And The Paths Of Rhythm",
  "Sonic Youth - Goo",
  "Ride - Nowhere",
  "My Bloody Valentine - Loveless",
  "Nirvana - Nevermind",
  "Crowded House - Woodface",
  "Cypress Hill - Cypress Hill",
  "Julian Cope - Peggy Suicide",
  "Gang Starr - Step In The Arena",
  "MC Solaar - Qui Sème Le Vent Récolte Le Tempo",
  "Jah Wobble's Invaders Of The Heart - Rising Above Bedlam",
  "Red Hot Chili Peppers - Blood Sugar Sex Magik",
  "Ice-T - O.G. Original Gangster",
  "Mudhoney - Every Good Boy Deserves Fudge",
  "Public Enemy - Apocalypse 91... The Enemy Strikes Black",
  "A Tribe Called Quest - The Low End Theory",
  "Pearl Jam - Ten",
  "Saint Etienne - Foxbase Alpha",
  "Sepultura - Arise",
  "Slint - Spiderland",
  "U2 - Achtung Baby",
  "The KLF - The White Room",
  "Massive* - Blue Lines",
  "Primal Scream - Screamadelica",
  "Teenage Fanclub - Bandwagonesque",
  "Metallica - Metallica",
  "Pavement - Slanted And Enchanted",
  "Aphex Twin - Selected Ambient Works 85-92",
  "Arrested Development - 3 Years, 5 Months And 2 Days In The Life Of...",
  "Koffi Olomidé* - Haut De Gamme - Koweït, Rive Gauche",
  "Morrissey - Your Arsenal",
  "Baaba Maal - Lam Toro",
  "Lemonheads* - It's A Shame About Ray",
  "Rage Against The Machine - Rage Against The Machine",
  "The Disposable Heroes Of Hiphoprisy - Hypocrisy Is The Greatest Luxury",
  "k.d. lang - Ingénue",
  "Dr. Dre - The Chronic",
  "R.E.M. - Automatic For The People",
  "The Pharcyde - Bizarre Ride II The Pharcyde",
  "Spiritualized - Lazer Guided Melodies",
  "Sugar (5) - Copper Blue",
  "Tom Waits - Bone Machine",
  "Sonic Youth - Dirty",
  "Stereo MC's - Connected",
  "Ministry - ΚΕΦΑΛΗΞΘ",
  "Tori Amos - Little Earthquakes",
  "Ice Cube - The Predator",
  "Pantera - Vulgar Display Of Power",
  "Alice In Chains - Dirt",
  "Nick Cave & The Bad Seeds - Henry's Dream",
  "Nusrat Fateh Ali Khan & Party - Devotional Songs",
  "P J Harvey* - Dry",
  "Suede - Suede",
  "Paul Weller - Wild Wood",
  "Smashing Pumpkins* - Siamese Dream",
  "The Auteurs - New Wave",
  "Liz Phair - Exile In Guyville",
  "The Afghan Whigs - Gentlemen",
  "Aimee Mann - Whatever",
  "Grant Lee Buffalo - Fuzzy",
  "Nirvana - In Utero",
  "Jamiroquai - Emergency On Planet Earth",
  "Pet Shop Boys - Very",
  "P J Harvey* - Rid Of Me",
  "Blur - Modern Life Is Rubbish",
  "Sheryl Crow - Tuesday Night Music Club",
  "The Fall - The Infotainment Scan",
  "Wu-Tang Clan - Enter The Wu-Tang (36 Chambers)",
  "Björk - Debut",
  "Orbital - Orbital",
  "Snoop Doggy Dogg* - Doggystyle",
  "Sebadoh - Bubble & Scrape",
  "The Boo Radleys - Giant Steps",
  "William Orbit - Strange Cargo III",
  "Method Man - Tical",
  "Frank Black - Teenager Of The Year",
  "Girls Against Boys - Venus Luxure No.1 Baby",
  "Jeru The Damaja - The Sun Rises In The East",
  "Pavement - Crooked Rain Crooked Rain",
  "Portishead - Dummy",
  "The Sabres Of Paradise - Haunted Dancehall",
  "Nas - Illmatic",
  "Beastie Boys - Ill Communication",
  "Elvis Costello - Brutal Youth",
  "Morrissey - Vauxhall And I",
  "TLC - CrazySexyCool",
  "Oasis (2) - Definitely Maybe",
  "Soundgarden - Superunknown",
  "Offspring* - Smash",
  "Drive Like Jehu - Yank Crime",
  "Blur - Parklife",
  "G. Love & Special Sauce - G. Love & Special Sauce",
  "Ali Farka Toure* With Ry Cooder - Talking Timbuktu",
  "Hole (2) - Live Through This",
  "Massive Attack - Protection",
  "Manic Street Preachers - The Holy Bible",
  "Suede - Dog Man Star",
  "The Notorious B.I.G.* - Ready To Die",
  "Jeff Buckley - Grace",
  "Orbital - Snivilisation",
  "Nirvana - MTV Unplugged In New York",
  "Nine Inch Nails - The Downward Spiral",
  "The Prodigy - Music For The Jilted Generation",
  "Green Day - Dookie",
  "Foo Fighters - Foo Fighters",
  "Garbage - Garbage",
  "Nightmares On Wax - Smokers Delight",
  "Tricky - Maxinquaye",
  "Chef Raekwon* - Only Built 4 Cuban Linx...",
  "The Smashing Pumpkins - Mellon Collie And The Infinite Sadness",
  "Rocket From The Crypt - Scream, Dracula, Scream!",
  "The Chemical Brothers - Exit Planet Dust",
  "2Pac - Me Against The World",
  "Elastica (2) - Elastica",
  "Supergrass - I Should Coco",
  "Radiohead - The Bends",
  "Guided By Voices - Alien Lanes",
  "Femi Kuti - Femi Kuti",
  "The Verve - A Northern Soul",
  "Genius* / GZA - Liquid Swords",
  "Pulp - Different Class",
  "Leftfield - Leftism",
  "D'Angelo - Brown Sugar",
  "Oasis (2) - (What's The Story) Morning Glory?",
  "Goldie - Timeless",
  "Alanis Morissette - Jagged Little Pill",
  "Screaming Trees - Dust",
  "Super Furry Animals - Fuzzy Logic",
  "Fatboy Slim - Better Living Through Chemistry",
  "Dr. Octagon - Dr. Octagon",
  "Stereolab - Emperor Tomato Ketchup",
  "Tortoise - Millions Now Living Will Never Die",
  "Beck - Odelay",
  "Belle And Sebastian* - Tigermilk",
  "DJ Shadow - Endtroducing.....",
  "Eels - Beautiful Freak",
  "The Divine Comedy - Casanova",
  "Fiona Apple - Tidal",
  "Wilco - Being There",
  "Sepultura - Roots",
  "Barry Adamson - Oedipus Schmoedipus",
  "Fun Lovin' Criminals - Come Find Yourself",
  "Maxwell - Maxwell's Urban Hang Suite",
  "The Charlatans - Tellin' Stories",
  "Manic Street Preachers - Everything Must Go",
  "Everything But The Girl - Walking Wounded",
  "Nick Cave And The Bad Seeds* - Murder Ballads",
  "L.T.J. Bukem* - Logical Progression",
  "Underworld - Second Toughest In The Infants",
  "The Jon Spencer Blues Explosion - Now I Got Worry",
  "The Cardigans - First Band On The Moon",
  "Marilyn Manson - Antichrist Superstar",
  "Fugees - The Score",
  "Ash - 1977",
  "Belle And Sebastian* - If You're Feeling Sinister",
  "Blur - Blur",
  "Radiohead - OK Computer",
  "Finley Quaye - Maverick A Strike",
  "Missy Misdemeanor Elliott* - Supa Dupa Fly",
  "The Chemical Brothers - Dig Your Own Hole",
  "Primal Scream - Vanishing Point",
  "Robert Wyatt - Shleep",
  "David Holmes - Lets Get Killed",
  "Sleater-Kinney - Dig Me Out",
  "Prodigy* - The Fat Of The Land",
  "Buena Vista Social Club - Buena Vista Social Club",
  "Nick Cave & The Bad Seeds - The Boatman's Call",
  "The Divine Comedy - A Short Album About Love",
  "Cornershop - When I Was Born For The 7th Time",
  "Daft Punk - Homework",
  "Robbie Williams - Life Thru A Lens",
  "Mariah Carey - Butterfly",
  "Supergrass - In It For The Money",
  "Bob Dylan - Time Out Of Mind",
  "Roni Size / Reprazent - New Forms",
  "Elliott Smith - Either / Or",
  "The Verve - Urban Hymns",
  "Spiritualized - Ladies And Gentlemen We Are Floating In Space",
  "System Of A Down - System Of A Down",
  'Bob Dylan - Live 1966 (The "Royal Albert Hall" Concert)',
  "Manu Chao - Clandestino",
  "Billy Bragg & Wilco - Mermaid Avenue",
  "Turbonegro - Apocalypse Dudes",
  "Fatboy Slim - You've Come A Long Way, Baby",
  "David Gray - White Ladder",
  "Lucinda Williams - Car Wheels On A Gravel Road",
  "Pulp - This Is Hardcore",
  "Madonna - Ray Of Light",
  "Lauryn Hill - The Miseducation Of Lauryn Hill",
  "Hole (2) - Celebrity Skin",
  "Mercury Rev - Deserter's Songs",
  "Queens Of The Stone Age - Queens Of The Stone Age",
  "AIR French Band* - Moon Safari",
  "Talvin Singh - OK",
  "Korn - Follow The Leader",
  "Kid Rock - Devil Without A Cause",
  "Boards Of Canada - Music Has The Right To Children",
  "Suba - São Paulo Confessions",
  "Khaled - Kenza",
  "XTC - Apple Venus Volume 1",
  "Incubus (2) - Make Yourself",
  "The Magnetic Fields - 69 Love Songs",
  "Travis - The Man Who",
  "Slipknot - Slipknot",
  "Beth Orton - Central Reservation",
  "Nitin Sawhney - Beyond Skin",
  "Death In Vegas - The Contino Sessions",
  "Moby - Play",
  "The Flaming Lips - The Soft Bulletin",
  "Les Rythmes Digitales - Darkdancer",
  "Le Tigre - Le Tigre",
  "Eminem - The Slim Shady LP",
  "Metallica With Michael Kamen Conducting The San Francisco Symphony Orchestra - S&M",
  "Bonnie 'Prince' Billy* - I See A Darkness",
  "Shack (3) - H.M.S. Fable",
  "Basement Jaxx - Remedy",
  "Red Hot Chili Peppers - Californication",
  "Sigur Rós - Ágætis Byrjun",
  "Doves - Lost Souls",
  "AIR - The Virgin Suicides",
  "Ryan Adams - Heartbreaker",
  "Bebel Gilberto - Tanto Tempo",
  "MJ Cole - Sincere",
  "Emmylou Harris - Red Dirt Girl",
  "Radiohead - Kid A",
  "U2 - All That You Can't Leave Behind",
  "Coldplay - Parachutes",
  "Elliott Smith - Figure 8",
  "Badly Drawn Boy - The Hour Of Bewilderbeast",
  "P J Harvey* - Stories From The City, Stories From The Sea",
  "eryKahBadu* - Mama's Gun",
  "Common - Like Water For Chocolate",
  "Mike Ladd - Welcome To The Afterfuture",
  "Red Snapper - Our Aim Is To Satisfy Red Snapper",
  "Eminem - The Marshall Mathers LP",
  "Goldfrapp - Felt Mountain",
  "Ute Lemper - Punishing Kiss",
  "Madonna - Music",
  "The Avalanches - Since I Left You",
  "OutKast - Stankonia",
  "Lambchop - Nixon",
  "Silver Jews - Bright Flight",
  "Björk - Vespertine",
  "Ryan Adams - Gold",
  "The Strokes - Is This It",
  "Gillian Welch - Time (The Revelator)",
  "Gotan Project - La Revancha Del Tango",
  "The White Stripes - White Blood Cells",
  "Jay-Z - The Blueprint",
  "Röyksopp - Melody A.M.",
  "Drive-By Truckers - Southern Rock Opera",
  "Super Furry Animals - Rings Around The World",
  "Jurassic 5 - Power In Numbers",
  "Wilco - Yankee Hotel Foxtrot",
  "Ms. Dynamite - A Little Deeper",
  "Norah Jones - Come Away With Me",
  "Coldplay - A Rush Of Blood To The Head",
  "The Coral - The Coral",
  "The Flaming Lips - Yoshimi Battles The Pink Robots",
  "Doves - The Last Broadcast",
  "Johnny Cash - American IV: The Man Comes Around",
  "Missy Elliott - Under Construction",
  "Bruce Springsteen - The Rising",
  "Beck - Sea Change",
  "The Roots - Phrenology",
  "The White Stripes - Elephant",
  "Yeah Yeah Yeahs - Fever To Tell",
  "OutKast - Speakerboxxx / The Love Below",
  "Dizzee Rascal - Boy In Da Corner",
  "The Mars Volta - De-Loused In The Comatorium",
  "Lightning Bolt - Wonderful Rainbow",
  "Devendra Banhart - Rejoicing In The Hands",
  "Nick Cave & The Bad Seeds - Abattoir Blues / The Lyre Of Orpheus",
  "Franz Ferdinand - Franz Ferdinand",
  "Kanye West - The College Dropout",
  "Cee-Lo Green* - Cee-Lo Green... Is The Soul Machine",
  "Mylo - Destroy Rock & Roll",
  "The Icarus Line - Penance Soirée",
  "The Streets - A Grand Don't Come For Free",
  "Rufus Wainwright - Want Two",
  "Ozomatli - Street Signs",
  "Morrissey - You Are The Quarry",
  "Arcade Fire - Funeral",
  "Green Day - American Idiot",
  "Common - Be",
  "Richard Hawley - Coles Corner",
  "Sufjan Stevens - Sufjan Stevens Invites You To: Come On Feel The Illinoise",
  "Amy Winehouse - Back To Black",
  "Lupe Fiasco - Lupe Fiasco's Food & Liquor",
  "Ghostface Killah - Fishscale",
  "Ali Farka Toure* - Savane",
  "Joanna Newsom - Ys",
  "Arctic Monkeys - Whatever People Say I Am, That's What I'm Not",
  "LCD Soundsystem - Sound Of Silver",
  "Radiohead - In Rainbows",
  "MIA* - Kala",
  "Justice (3) - † (Cross)",
  "Q-Tip - The Renaissance",
  "Elbow - The Seldom Seen Kid",
  "Portishead - Third",
  "Slipknot - All Hope Is Gone",
  "TV On The Radio - Dear Science",
  "Fleet Foxes - Fleet Foxes",
  "MGMT - Oracular Spectacular",
  "Grizzly Bear - Veckatimest",
  "Fever Ray - Fever Ray",
  "Animal Collective - Merriweather Post Pavilion",
  "Bill Callahan - Sometimes I Wish We Were An Eagle",
  "Yeah Yeah Yeahs - It's Blitz!",
  "Dirty Projectors - Bitte Orca",
  "The XX - xx",
  "Wild Beasts - Two Dancers",
  "The National - High Violet",
  "Beach House - Teen Dream",
  "The Black Keys - Brothers",
  "Kanye West - My Beautiful Dark Twisted Fantasy",
  "John Grant - Queen Of Denmark",
  "Janelle Monáe - The ArchAndroid",
  "Deerhunter - Halcyon Digest",
  "Arcade Fire - The Suburbs"
]

export default Albuns
